In [1]:
import numpy as np

In [2]:
normal_list=[1,2,3]
numpy_array=np.array(normal_list)

In [3]:
numpy_array

array([1, 2, 3])

In [4]:
normal_list=list(range(1,100))
numpy_array=np.array(normal_list)

In [6]:
%%time

a=[x-1 for x in normal_list]
print(a)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98]
CPU times: user 2.81 ms, sys: 0 ns, total: 2.81 ms
Wall time: 7.08 ms


In [7]:
%%time

a=[]
for x in normal_list:
    a.append(x-1)

print(a)    


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98]
CPU times: user 2.2 ms, sys: 137 µs, total: 2.34 ms
Wall time: 5.7 ms


In [8]:
%%time

a=numpy_array-1
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98]
CPU times: user 0 ns, sys: 3.83 ms, total: 3.83 ms
Wall time: 8.86 ms


In [9]:
a=np.array([4,1,2,5,6,7])

In [10]:
print("numpy array a:{}\n type of a: {}\n".format(a,type(a)))

numpy array a:[4 1 2 5 6 7]
 type of a: <class 'numpy.ndarray'>



In [11]:
print("what is the 4th element?:{}".format(a[3]))

what is the 4th element?:5


In [15]:
a=np.array([[1,2],
            [3,4],
            [5,6]])
print("array a:{}\n array shape:{}".format(a,a.shape))

array a:[[1 2]
 [3 4]
 [5 6]]
 array shape:(3, 2)


In [16]:
rows , cols = a.shape

In [18]:
print("rows:{}\ncols:{}\n".format(rows,cols))

rows:3
cols:2



In [20]:
a=np.zeros((4,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
a=np.ones((4,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [25]:
a=np.eye((5))
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
a=np.full((4,4),555)
a

array([[555, 555, 555, 555],
       [555, 555, 555, 555],
       [555, 555, 555, 555],
       [555, 555, 555, 555]])

In [28]:
a=np.random.randint(1,30,size=(4,3))
a

array([[13, 23,  1],
       [ 6,  6, 26],
       [ 1, 27, 14],
       [ 3,  8, 24]])

In [30]:
a=np.random.randint(4,99,size=(8,8))
a

array([[87, 25, 69, 44, 13, 31, 10, 23],
       [26, 11, 89, 81,  5, 95, 98, 11],
       [73, 77, 67, 61, 91, 39, 73, 65],
       [34, 80, 93, 33, 21, 39, 83,  6],
       [69, 86, 73, 55, 15, 53, 90, 14],
       [55, 33, 20, 94, 95, 37, 17, 72],
       [97, 67, 31, 34, 19, 78, 96, 65],
       [94,  7, 84, 74, 88, 12,  4, 73]])

In [31]:
a[-1]

array([94,  7, 84, 74, 88, 12,  4, 73])

In [32]:
a[:3]

array([[87, 25, 69, 44, 13, 31, 10, 23],
       [26, 11, 89, 81,  5, 95, 98, 11],
       [73, 77, 67, 61, 91, 39, 73, 65]])

In [33]:
a[:3,:]

array([[87, 25, 69, 44, 13, 31, 10, 23],
       [26, 11, 89, 81,  5, 95, 98, 11],
       [73, 77, 67, 61, 91, 39, 73, 65]])

In [34]:
a[:,:3]

array([[87, 25, 69],
       [26, 11, 89],
       [73, 77, 67],
       [34, 80, 93],
       [69, 86, 73],
       [55, 33, 20],
       [97, 67, 31],
       [94,  7, 84]])

In [35]:
a[:3,:2]

array([[87, 25],
       [26, 11],
       [73, 77]])

In [36]:
a[-3:,-2:]

array([[17, 72],
       [96, 65],
       [ 4, 73]])

In [38]:
print("step:\n{}".format(a[::2]))

step:
[[87 25 69 44 13 31 10 23]
 [73 77 67 61 91 39 73 65]
 [69 86 73 55 15 53 90 14]
 [97 67 31 34 19 78 96 65]]


In [39]:
x=50
b=a>x

In [40]:
b

array([[ True, False,  True, False, False, False, False, False],
       [False, False,  True,  True, False,  True,  True, False],
       [ True,  True,  True,  True,  True, False,  True,  True],
       [False,  True,  True, False, False, False,  True, False],
       [ True,  True,  True,  True, False,  True,  True, False],
       [ True, False, False,  True,  True, False, False,  True],
       [ True,  True, False, False, False,  True,  True,  True],
       [ True, False,  True,  True,  True, False, False,  True]])

In [41]:
a[b]

array([87, 69, 89, 81, 95, 98, 73, 77, 67, 61, 91, 73, 65, 80, 93, 83, 69,
       86, 73, 55, 53, 90, 55, 94, 95, 72, 97, 67, 78, 96, 65, 94, 84, 74,
       88, 73])

In [42]:
a[a>x]

array([87, 69, 89, 81, 95, 98, 73, 77, 67, 61, 91, 73, 65, 80, 93, 83, 69,
       86, 73, 55, 53, 90, 55, 94, 95, 72, 97, 67, 78, 96, 65, 94, 84, 74,
       88, 73])

In [43]:
a==90

array([[False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False,  True, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False]])

In [44]:
a[a%2==0]

array([44, 10, 26, 98, 34, 80,  6, 86, 90, 14, 20, 94, 72, 34, 78, 96, 94,
       84, 74, 88, 12,  4])

In [47]:
a=np.random.randint(0,10,size=(5,5))
b=np.random.randint(0,10,size=(5,5))

In [49]:
print("array a:\n{}\narray b\n:{}".format(a,b))

array a:
[[8 1 2 0 3]
 [9 3 8 2 4]
 [6 6 1 9 2]
 [9 4 5 9 4]
 [6 0 2 9 0]]
array b
:[[5 0 5 0 7]
 [0 9 5 0 7]
 [9 4 2 4 0]
 [6 5 5 6 3]
 [0 9 7 8 7]]


In [50]:
a+b

array([[13,  1,  7,  0, 10],
       [ 9, 12, 13,  2, 11],
       [15, 10,  3, 13,  2],
       [15,  9, 10, 15,  7],
       [ 6,  9,  9, 17,  7]])

In [51]:
a-b

array([[ 3,  1, -3,  0, -4],
       [ 9, -6,  3,  2, -3],
       [-3,  2, -1,  5,  2],
       [ 3, -1,  0,  3,  1],
       [ 6, -9, -5,  1, -7]])

In [52]:
a*b

array([[40,  0, 10,  0, 21],
       [ 0, 27, 40,  0, 28],
       [54, 24,  2, 36,  0],
       [54, 20, 25, 54, 12],
       [ 0,  0, 14, 72,  0]])

In [53]:
a/b

<ipython-input-53-aae42d317509>:1: RuntimeWarning: divide by zero encountered in true_divide
  a/b
<ipython-input-53-aae42d317509>:1: RuntimeWarning: invalid value encountered in true_divide
  a/b


array([[1.6       ,        inf, 0.4       ,        nan, 0.42857143],
       [       inf, 0.33333333, 1.6       ,        inf, 0.57142857],
       [0.66666667, 1.5       , 0.5       , 2.25      ,        inf],
       [1.5       , 0.8       , 1.        , 1.5       , 1.33333333],
       [       inf, 0.        , 0.28571429, 1.125     , 0.        ]])

In [54]:
a.dot(b)

array([[ 58,  44,  70,  32,  84],
       [129, 105, 114,  76, 118],
       [ 93, 121, 121,  74, 125],
       [144, 137, 148, 106, 146],
       [102,  53,  79,  62,  69]])

In [55]:
np.dot(a,b)

array([[ 58,  44,  70,  32,  84],
       [129, 105, 114,  76, 118],
       [ 93, 121, 121,  74, 125],
       [144, 137, 148, 106, 146],
       [102,  53,  79,  62,  69]])

In [56]:
a

array([[8, 1, 2, 0, 3],
       [9, 3, 8, 2, 4],
       [6, 6, 1, 9, 2],
       [9, 4, 5, 9, 4],
       [6, 0, 2, 9, 0]])

In [58]:
a.T

array([[8, 9, 6, 9, 6],
       [1, 3, 6, 4, 0],
       [2, 8, 1, 5, 2],
       [0, 2, 9, 9, 9],
       [3, 4, 2, 4, 0]])

In [59]:
a=np.random.randint(0,10,size=(5,5))
b=np.random.randint(0,10,size=(5))

In [61]:
a

array([[2, 5, 7, 3, 6],
       [6, 8, 3, 4, 1],
       [3, 5, 4, 2, 5],
       [9, 9, 0, 7, 3],
       [8, 6, 7, 9, 4]])

In [62]:
b

array([1, 3, 8, 3, 3])

In [63]:
a+b

array([[ 3,  8, 15,  6,  9],
       [ 7, 11, 11,  7,  4],
       [ 4,  8, 12,  5,  8],
       [10, 12,  8, 10,  6],
       [ 9,  9, 15, 12,  7]])

In [64]:
b.T

array([1, 3, 8, 3, 3])

In [66]:
b.T

array([1, 3, 8, 3, 3])

In [67]:
a+b.T

array([[ 3,  8, 15,  6,  9],
       [ 7, 11, 11,  7,  4],
       [ 4,  8, 12,  5,  8],
       [10, 12,  8, 10,  6],
       [ 9,  9, 15, 12,  7]])

In [68]:
b.reshape(-1,1)

array([[1],
       [3],
       [8],
       [3],
       [3]])

In [69]:
a+b.reshape(-1,1)

array([[ 3,  6,  8,  4,  7],
       [ 9, 11,  6,  7,  4],
       [11, 13, 12, 10, 13],
       [12, 12,  3, 10,  6],
       [11,  9, 10, 12,  7]])